version: '3.8'
services:

    #php server
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=production
        environment:
            - APP_ENV=production
            - CONTAINER_ROLE=app
            - DB_HOST=database
            - DB_DATABASE=cuoiky
            - DB_USERNAME=main
            - DB_PASSWORD=1234
            - DB_PORT=3306
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            - database


    #database
    database:
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=cuoiky
            - MYSQL_USER=main
            - MYSQL_PASSWORD=1234
            - MYSQL_ROOT_PASSWORD=1234
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data: ~
