version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: my-laravel-app
        ports:
            - "8000:8000"
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - APP_KEY=your_app_key
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=your_database
            - DB_USERNAME=your_username
            - DB_PASSWORD=your_password
        volumes:
            - .:/var/www
        depends_on:
            - db

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: localhost
            MYSQL_USER: root
            MYSQL_PASSWORD:
        ports:
            - "3306:3306"
